### ISSUE TITLE
Packages folder. vs folder must be in .gitignore file

### ISSUE THREAD

**Issue by anomepani** [saineshwar/Angular-7-Project-with-ASP.NET-CORE-APIS#1]
"Packages" and ".vs" folder must be in .gitignore file.
".vs" folder have ide related setting for user. 
"Packages" is installed or restore by Nuget package so it's increased project or source code,  which is not required to put in source control

**Comment by saineshwar** [comment]
Will do it and update repo

**Comment by dkaushikl** [comment]
Merge pull Request - https://github.com/saineshwar/Angular-7-Project-with-ASP.NET-CORE-APIS/pull/2
