### ISSUE TITLE
No navigation after login. How routing working?

### ISSUE THREAD

**Issue by himalayagarg** [saineshwar/Angular-7-Project-with-ASP.NET-CORE-APIS#11]
Hi, First of all thank you for the code developed yet.  I am successfully able to login (saw token in response), but login did not take me anywhere. How routing is working?

**Comment by anomepani** [comment]
Take a look at below link. And let me know does it work for you. 
https://github.com/saineshwar/Angular-7-Project-with-ASP.NET-CORE-APIS/blob/master/README.md#how-to-run-both-projects-side-by-side

**Comment by himalayagarg** [comment]
> Take a look at below link. And let me know does it work for you.
> https://github.com/saineshwar/Angular-7-Project-with-ASP.NET-CORE-APIS/blob/master/README.md#how-to-run-both-projects-side-by-side

Those steps I have already took. API is working and I am getting success response back from API after login. But problem was it was not navigating away from login page.
Anyways, I just tried manually putting URL -[http://localhost:myport/#/User]( http://localhost:<port>/#/User) and it worked. Thank you!

**Comment by anomepani** [comment]
Okay for now I am Closing this issue

**Comment by himalayagarg** [comment]
> Okay for now I am Closing this issue

I added this line in **LoginComponent** after successful login and it worked.

For UserType 1: > `localStorage.setItem('AdminUser', response.token);`

For UserType 2: > `localStorage.setItem('currentUser', response.token);`
