### ISSUE TITLE
Missing API Listing page or API Detail page in Asp.net core Project.

### ISSUE THREAD

**Issue by anomepani** [saineshwar/Angular-7-Project-with-ASP.NET-CORE-APIS#3]
I have run only Asp.Net Core API Project and want to explore different endpoints of WebAPI but not able to see any navigation or detail to verify is API is working or not?

@saineshwar , What you think Can we add Swagger or similar tool for API Documentation?

**Comment by saineshwar** [comment]
@anomepani  we can do it as an individual contributor I tried to build this much if you can help we can make it good product.

**Comment by anomepani** [comment]
Thanks, @saineshwar I will do my best.
