### ISSUE TITLE
User Friendly exception handling is missing for API Project

### ISSUE THREAD

**Issue by anomepani** [saineshwar/Angular-7-Project-with-ASP.NET-CORE-APIS#4]
Angular 7 or any other Front end framework depends on API which mostly returns a JSON response. Here consider if API Server is down or while accessing any API if an exception occurs it should return JSON response with a valid status which identifies success or error response based on that Front end developer (Here In Angular App) should display a notification in red or green or any warning color.

In Current system it returning ErrorView (HTML response).

**Comment by saineshwar** [comment]
Hi @anomepani  you can contribute this repo to make is better I am not UI developer but I tried to create a project which helps the developer to at least know how this application works. I know this project has issues.

**Comment by anomepani** [comment]
I understand your efforts and purpose @saineshwar. I am just creating issue not to point of negative or positive points but to make this project at an up level so more contributor can participate and togather we can improve as industry ready project not for just learning purpose.
Sure I will start to contribute wherever possible.
